base_path: '../../data/vitaldb'
holdout_subject_size: 100
test_size: 0.20
modality_name2path:
  'ABP': '/home/coder/workspace/updown/physiome_hetero/ckpt/neuronet/ABP/model/best_model.pth'
  'ECG': '/home/coder/workspace/updown/physiome_hetero/ckpt/neuronet/ECG/model/best_model.pth'
  'PPG': '/home/coder/workspace/updown/physiome_hetero/ckpt/neuronet/PPG/model/best_model.pth'
  'CVP': '/home/coder/workspace/updown/physiome_hetero/ckpt/neuronet/CVP/model/best_model.pth'
sfreq: 100
rfreq: 100
data_scaler: false
class_downsampling: true

train_epochs: 50
train_warmup_epoch: 1
train_base_learning_rate: 0.0001
train_batch_size: 128
train_batch_accumulation: 1

second: 60
time_window: 3
time_step: 3
backbone_embed_dim: 512
backbone_num_frames: 20
encoder_embed_dim: 512
encoder_heads: 8
encoder_depths: 4
decoder_embed_dim: 256
decoder_heads: 8
decoder_depths: 3
decoder_recon_depths: 8
projection_hidden:
  - 1024
  - 512
temperature: 0.1
mask_ratio: 0.4

lora_r: 4
lora_alpha: 16
lora_dropout: 0.05

print_point: 20
ckpt_path: '/home/coder/workspace/updown/physiome_hetero/ckpt/'
model_name: 'physiome'
